// <auto-generated />
namespace Tests
{
    using System;
    using NUnit.Framework;
    using Task2FindNumber;

    /// <summary>
    /// Class for tests
    /// </summary>
    [TestFixture]
    public class FinderTests
    {
        /// <summary>
        /// If value out of range
        /// </summary>
        [Test]
        public void FindNextBiggerNumber_ThrowsArgumentException()
        {
            long time = 0;
            Assert.Throws<ArgumentException>(() => FindNumber.FindNextBiggerNumber(-1, out time));
        }

        /// <summary>
        /// Method for testing 
        /// </summary>
        /// <param name="number">initial number</param>
        /// <returns>Next bigger value</returns>
        [TestCase(12, ExpectedResult = 21)]
        [TestCase(513, ExpectedResult = 531)]
        [TestCase(2017, ExpectedResult = 2071)]
        [TestCase(414, ExpectedResult = 441)]
        [TestCase(144, ExpectedResult = 414)]
        [TestCase(1234321, ExpectedResult = 1241233)]
        [TestCase(1234126, ExpectedResult = 1234162)]
        [TestCase(3456432, ExpectedResult = 3462345)]
        [TestCase(10, ExpectedResult = -1)]
        [TestCase(20, ExpectedResult = -1)]
        public int FindNextBiggerNumber_Righttest(int number)
        {
            long time = 0;
            return FindNumber.FindNextBiggerNumber(number, out time);
        }
    }
}